
<h3 class="page-header"><i class="glyphicon-group"></i><span style="margin: 6px;">Reviews</span></h3>

<div class="dataTables_wrapper form-inline" role="grid">
	<div class="row-fluid">
		<div class="span6">

		</div>
	</div>
	<table class="table table-striped table-bordered table-hover dataTable" aria-describedby="example-datatables_info">
		<thead>
			<tr>
				<th style="text-align: center;">#</th>
				<th style="text-align: center;">User ID</th>
				<th style="text-align: center;">Song ID</th>
				<th style="text-align: center;">Stars</th>
				<th style="text-align: center;">Text</th>
			</tr>
		</thead>

		<tbody>

		<?php foreach($this->reviews as $review) : ?>
			<tr class="odd">
				<td style="text-align: center;"><?php echo $review['user_id']; ?></td>
				<td style="text-align: center;"><?php echo $review['song_id']; ?></td>
				<td style="text-align: center;"><?php echo $review['star']; ?></td>
				<td style="text-align: center;"><?php echo $review['review_text']; ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>