
<h3 class="page-header"><i class="glyphicon-group"></i><span style="margin: 6px;">Users</span></h3>

<div class="dataTables_wrapper form-inline" role="grid">
	<div class="row-fluid">
		<div class="span6">

		</div>
	</div>
	<table class="table table-striped table-bordered table-hover dataTable" aria-describedby="example-datatables_info">
		<thead>
			<tr>
				<th style="text-align: center;">#</th>
				<th style="text-align: center;">Username</th>
				<th style="text-align: center;">Email</th>
				<th style="text-align: center;">Name</th>
				<th style="text-align: center;">Family</th>
				<th style="text-align: center;">Actions</th>
			</tr>
		</thead>

		<tbody>

		<?php foreach($this->users as $user) : ?>
			<tr class="odd">
				<td style="text-align: center;"><?php echo $user['id']; ?></td>
				<td style="text-align: center;"><?php echo $user['username']; ?></td>
				<td style="text-align: center;"><?php echo $user['email']; ?></td>
				<td style="text-align: center;"><?php echo $user['name']; ?></td>
				<td style="text-align: center;"><?php echo $user['family']; ?></td>
				<td class="span1" style="text-align: center;">
					<div class="btn-group">
						<a href="/add/addplaylist/user_id/<?php echo $user['id'];?>" class="btn btn-mini btn-success"><i class="icon-music"></i> Add playlist</a>
						<a href="/add/addreview/user_id/<?php echo $user['id'];?>" class="btn btn-mini btn-warning"><i class="icon-pencil"></i> Add Review</a>
						<a href="/add/order/user_id/<?php echo $user['id'];?>" class="btn btn-mini btn-info"><i class="icon-dollar"></i> New Order</a>
					</div>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>


<h3 class="page-header"><i class="icon-file-text"></i><span style="margin: 6px;">Reviews</span></h3>

<div class="dataTables_wrapper form-inline" role="grid">
	<div class="row-fluid">
		<div class="span6">

		</div>
	</div>
	<table class="table table-striped table-bordered table-hover dataTable">
		<thead>
		<tr>
			<th style="text-align: center;">User ID</th>
			<th style="text-align: center;">Song ID</th>
			<th style="text-align: center;">Stars</th>
			<th style="text-align: center;">Text</th>
		</tr>
		</thead>

		<tbody>

		<?php foreach($this->reviews as $review) : ?>
			<tr class="odd">
				<td style="text-align: center;"><?php echo $review['user_id']; ?></td>
				<td style="text-align: center;"><?php echo $review['song_id']; ?></td>
				<td style="text-align: center;"><?php echo $review['star']; ?></td>
				<td style="text-align: center;"><?php echo $review['review_text']; ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>


<h3 class="page-header"><i class="icon-music"></i><span style="margin: 6px;">Songs</span></h3>

<div class="dataTables_wrapper form-inline" role="grid">
	<div class="row-fluid">
		<div class="span6">

		</div>
	</div>
	<table class="table table-striped table-bordered table-hover dataTable">
		<thead>
		<tr>
			<th style="text-align: center;">#</th>
			<th style="text-align: center;">Album ID</th>
			<th style="text-align: center;">Title</th>
			<th style="text-align: center;">Duration</th>
			<th style="text-align: center;">Price</th>
		</tr>
		</thead>

		<tbody>

		<?php foreach($this->songs as $song) : ?>
			<tr class="odd">
				<td style="text-align: center;"><?php echo $song['id']; ?></td>
				<td style="text-align: center;"><?php echo $song['album_id']; ?></td>
				<td style="text-align: center;"><?php echo $song['title']; ?></td>
				<td style="text-align: center;"><?php echo $song['duration']; ?></td>
				<td style="text-align: center;"><?php echo $song['price']; ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>