<div class="row-fluid">
	<div class="span6">
		<h4>Add entries</h4>
		<table class="table table-borderless">

			<tbody>
			<tr>
				<td><a type="button" class="btn btn-primary" href="/add/newalbum">Add Album</a></td>
			</tr>
			<tr>
				<td><a type="button" class="btn btn-success" href="/add/newsong">Add song</a></td>
			</tr>
			<tr>
				<td><a type="button" class="btn btn-danger" href="/add/newartist">Add artist</a></td>
			</tr>
			<tr>
				<td><a type="button" class="btn btn-warning" href="/add/newuser">Add user</a></td>
			</tr>
			</tbody>
		</table>
	</div>
	<div class="span6">
		<form class="form-horizontal form-box" action="/add/query">
			<h4 class="form-box-header">Direct Query</h4>
				<div class="control-group">
					<label class="control-label" for="example-textarea-elastic">Query</label>
					<div class="controls">
						<textarea name="query" class="textarea-elastic" rows="3" cols="38"></textarea>
					</div>
				</div>
					<input style="margin: 20px;" class="btn btn-success" type="submit">
		</form>
	</div>
</div>
