<form class="form-horizontal form-box" action="/add/newartist" method="post">
	<h4 class="form-box-header">Add new artist</h4>
	<div class="form-box-content">

		<div class="control-group">
			<label class="control-label">Name</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="name">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Family</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="family">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="example-textarea-large">Description</label>
			<div class="controls">
				<textarea id="example-textarea-large" class="textarea-large" rows="7" name="description" cols="60"></textarea>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="example-textarea-large">Genres</label>
			<div class="controls">
				<textarea id="example-textarea-large" class="textarea-large" rows="9" name="genres" cols="30"></textarea>
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-success"><i class="icon-save"></i> Save</button>
		</div>

	</div>
</form>