<form class="form-horizontal form-box" action="/add/newalbum" method="post">
	<h4 class="form-box-header">Add new album</h4>
	<div class="form-box-content">

		<div class="control-group">
			<label class="control-label">Title</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="title">
				<span class="help-block">Title of Album</span>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Release year</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="release_year">
				<span class="help-block">Release year of album</span>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Price</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="price">
				<span class="help-block">Price of album</span>
			</div>
		</div>

		<div class="control-group">
			<label class="control-label" for="example-textarea-large">Description</label>
			<div class="controls">
				<textarea id="example-textarea-large" class="textarea-large" rows="7" name="description" cols="60"></textarea>
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-success"><i class="icon-save"></i> Save</button>
		</div>

	</div>
</form>