<form class="form-horizontal form-box" action="/add/newuser" method="post">
	<h4 class="form-box-header">Add new user</h4>
	<div class="form-box-content">

		<div class="control-group">
			<label class="control-label">Name</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="name">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Family</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="family">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Email</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="email">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Username</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="username">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Password</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="password">
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-success"><i class="icon-save"></i> Save</button>
		</div>

	</div>
</form>