<form class="form-horizontal form-box" action="/add/order/user_id/<?php echo $this->user_id;?>" method="post">
	<h4 class="form-box-header">Add new Orders</h4>
	<div class="form-box-content">

		<div class="control-group">
			<label class="control-label" for="example-textarea-large">Song IDs</label>
			<div class="controls">
				<textarea id="example-textarea-large" class="textarea-large" rows="9" name="ids" cols="30"></textarea>
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-success"><i class="icon-save"></i> Save</button>
		</div>

	</div>
</form>